# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-26 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0002_auto_20180413_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functiontask',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
