# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-26 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodic_task', '0002_auto_20190103_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodictaskhistory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
