# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-26 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmaker', '0005_auto_20180823_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmaker',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
